### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by smallmaster1** [ChenJiahao031008/Numerical_Optimization#1]
您的代码似乎有问题。第一是初始点生成混乱，第二是改好第一点后，似乎没有了优化的过程，生成了一条直线。希望能够得到您的解答，谢谢。

**Comment by array-svg** [comment]
> 您好，关于初始点生成混乱能举个例子吗？没有优化过程生成了一条直线这一点能po一张
对应的图方便分析吗？

**Comment by smallmaster1** [comment]
> > 您好，关于初始点生成混乱能举个例子吗？没有优化过程生成了一条直线这一点能po一张
> > 对应的图方便分析吗？

**Comment by smallmaster1** [comment]
> > > 您好，关于初始点生成混乱能举个例子吗？没有优化过程生成了一条直线这一点能po一张
> > > 对应的图方便分析吗？

不好意思，是我个人操作有误，我没有对lbfgs.hpp中缺失的代码进行补全
